; PlatformIO Project Configuration File

[env:esp-wrover-kit]
platform = espressif32@^6.5.0
board = esp-wrover-kit
framework = arduino

board_build.partitions = no_ota.csv

upload_protocol = esptool
upload_port = COM10
upload_speed = 38400

upload_flags =
    --before
    default_reset
    --after
    no_reset

monitor_port = COM10
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -Ofast
    -DAUDIOKIT_BOARD=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    bblanchon/ArduinoJson @ ^6.16.1
    Wire
    https://github.com/pschatzmann/arduino-audiokit-hal

; build_type = debug